[project]
name = "mcp-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bm25s>=0.2.10",
    "mcp[cli]>=1.6.0",
    "starlette>=0.46.2",
]
